FROM python:3.12-slim

WORKDIR /rag-app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /rag-app/

EXPOSE 8501

ENTRYPOINT ["uvicorn"]
CMD ["agent:app", "--host", "0.0.0.0", "--port", "8501"]